/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecruitRouteImport } from './routes/recruit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VnRouteImport } from './routes/vn'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminComplianceRouteImport } from './routes/admin/compliance'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as CandidateCopilotRouteImport } from './routes/candidate/copilot'
import { Route as CandidateJobsRouteImport } from './routes/candidate/jobs'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter/index'
import { Route as RecruiterHubRouteImport } from './routes/recruiter/hub'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter/jobs'
import { Route as RecruiterProfileRouteImport } from './routes/recruiter/profile'
import { Route as RecruiterTalentRouteImport } from './routes/recruiter/talent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitRoute = RecruitRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VnRoute = VnRouteImport.update({
  id: '/vn',
  path: '/vn',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/admin/compliance',
  path: '/admin/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateCopilotRoute = CandidateCopilotRouteImport.update({
  id: '/candidate/copilot',
  path: '/candidate/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/candidate/jobs',
  path: '/candidate/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/recruiter/',
  path: '/recruiter/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterHubRoute = RecruiterHubRouteImport.update({
  id: '/recruiter/hub',
  path: '/recruiter/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/recruiter/jobs',
  path: '/recruiter/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterProfileRoute = RecruiterProfileRouteImport.update({
  id: '/recruiter/profile',
  path: '/recruiter/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterTalentRoute = RecruiterTalentRouteImport.update({
  id: '/recruiter/talent',
  path: '/recruiter/talent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vn': typeof VnRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/candidate/copilot': typeof CandidateCopilotRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/hub': typeof RecruiterHubRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vn': typeof VnRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/candidate/copilot': typeof CandidateCopilotRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/hub': typeof RecruiterHubRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/candidates': typeof CandidatesRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vn': typeof VnRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/candidate/copilot': typeof CandidateCopilotRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/recruiter/hub': typeof RecruiterHubRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/profile': typeof RecruiterProfileRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/candidates'
    | '/compliance'
    | '/copilot'
    | '/jobs'
    | '/login'
    | '/profile'
    | '/recruit'
    | '/sitemap.xml'
    | '/vn'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/compliance'
    | '/candidate/copilot'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/recruiter/hub'
    | '/recruiter/jobs'
    | '/recruiter/profile'
    | '/recruiter/talent'
    | '/admin/'
    | '/candidate/'
    | '/recruiter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/candidates'
    | '/compliance'
    | '/copilot'
    | '/jobs'
    | '/login'
    | '/profile'
    | '/recruit'
    | '/sitemap.xml'
    | '/vn'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/compliance'
    | '/candidate/copilot'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/recruiter/hub'
    | '/recruiter/jobs'
    | '/recruiter/profile'
    | '/recruiter/talent'
    | '/admin'
    | '/candidate'
    | '/recruiter'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/candidates'
    | '/compliance'
    | '/copilot'
    | '/jobs'
    | '/login'
    | '/profile'
    | '/recruit'
    | '/sitemap.xml'
    | '/vn'
    | '/admin/analytics'
    | '/admin/candidates'
    | '/admin/compliance'
    | '/candidate/copilot'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/recruiter/hub'
    | '/recruiter/jobs'
    | '/recruiter/profile'
    | '/recruiter/talent'
    | '/admin/'
    | '/candidate/'
    | '/recruiter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CandidatesRoute: typeof CandidatesRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecruitRoute: typeof RecruitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VnRoute: typeof VnRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  CandidateCopilotRoute: typeof CandidateCopilotRoute
  CandidateJobsRoute: typeof CandidateJobsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  RecruiterHubRoute: typeof RecruiterHubRoute
  RecruiterJobsRoute: typeof RecruiterJobsRoute
  RecruiterProfileRoute: typeof RecruiterProfileRoute
  RecruiterTalentRoute: typeof RecruiterTalentRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruit': {
      id: '/recruit'
      path: '/recruit'
      fullPath: '/recruit'
      preLoaderRoute: typeof RecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vn': {
      id: '/vn'
      path: '/vn'
      fullPath: '/vn'
      preLoaderRoute: typeof VnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/copilot': {
      id: '/candidate/copilot'
      path: '/candidate/copilot'
      fullPath: '/candidate/copilot'
      preLoaderRoute: typeof CandidateCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/candidate/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/hub': {
      id: '/recruiter/hub'
      path: '/recruiter/hub'
      fullPath: '/recruiter/hub'
      preLoaderRoute: typeof RecruiterHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/profile': {
      id: '/recruiter/profile'
      path: '/recruiter/profile'
      fullPath: '/recruiter/profile'
      preLoaderRoute: typeof RecruiterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/talent': {
      id: '/recruiter/talent'
      path: '/recruiter/talent'
      fullPath: '/recruiter/talent'
      preLoaderRoute: typeof RecruiterTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CandidatesRoute: CandidatesRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecruitRoute: RecruitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VnRoute: VnRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  CandidateCopilotRoute: CandidateCopilotRoute,
  CandidateJobsRoute: CandidateJobsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  RecruiterHubRoute: RecruiterHubRoute,
  RecruiterJobsRoute: RecruiterJobsRoute,
  RecruiterProfileRoute: RecruiterProfileRoute,
  RecruiterTalentRoute: RecruiterTalentRoute,
  AdminIndexRoute: AdminIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
